### ISSUE TITLE
發表文章 Content 似乎有靈性的機率性運行、不運行

### ISSUE THREAD

**Issue by Kantai235** [init-engineer/init.engineer#11]
純靠北工程師最近有一個 Bug 讓我百思不得其解
這是發表文章時，產生 Content 內文的方法

![截圖 2019-12-24 上午10 02 29](https://user-images.githubusercontent.com/11679504/71388822-e75ce080-2634-11ea-9850-d71871c98222.png)

很明顯一定會帶入匿名發文連結、全平台留言連結，以及最近加入的去 GitHub 幫忙按星星
可是！
理論上我會獲得這些資訊，在測試時也確實獲得這些資訊
部署上去後，我有時候正常運行，有時候那句新加上去的卻不會給我戴上去
WTF
寫死的程式，還能夠有機率性的運行喔

**Comment by Kantai235** [comment]
# 解決辦法
1. 重新開機。

**Comment by cheetosysst** [comment]
太神了這個解決法
