### ISSUE TITLE
送出投稿的彈窗叫我來發issue

### ISSUE THREAD

**Issue by JayDing** [init-engineer/init.engineer#124]
**描述錯誤**
如題

**重現**
重現行為的步驟：
1. 轉到最後確認的步驟
2. 按返回到最一開始修改內容
3. 再轉到最後確認的步驟
4. 點擊 '送出投稿'
5. 看到錯誤。

**預期行為**
完成投稿

**截圖**
![F5597D91-5B64-4ACD-AF09-8F3698EED96A](https://user-images.githubusercontent.com/6994536/210030901-1c4a2608-07ea-44b9-a8a6-697020cd7870.png)

**裝置與環境(請填寫以下訊息):**
* 設備: iPhone 14
* 操作系統: iOS 16.1.1
* 瀏覽器: Safari
* 版本: 16

**Comment by leave3310** [comment]
剛剛想發文也遇到同樣的問題！
看network回傳 500
![截圖 2024-08-03 下午6 11 09](https://github.com/user-attachments/assets/e133eb99-7de9-400e-95af-5cbb74552ba4)

裝置與環境(請填寫以下訊息):

設備: Apple M2 Pro
操作系統: mac OS sonoma 14.5
瀏覽器: edge
版本: 127.0.2651.86

**Comment by Kantai235** [comment]
> 剛剛想發文也遇到同樣的問題！
> 
> 看network回傳 500
> 
> ![截圖 2024-08-03 下午6 11 09](https://github.com/user-attachments/assets/e133eb99-7de9-400e-95af-5cbb74552ba4)
> 
> 
> 
> 裝置與環境(請填寫以下訊息):
> 
> 
> 
> 設備: Apple M2 Pro
> 
> 操作系統: mac OS sonoma 14.5
> 
> 瀏覽器: edge
> 
> 版本: 127.0.2651.86

稍微檢查了一下系統，應該是投稿時，寄信通知部分的功能出問題了，今日會員系統被來自各種奇怪的來源狂戳當中，導致 Gmail 被冷靜冷靜，目前應該已經修復完畢了，感謝您的回報 🥰

**Comment by yoyo890121** [comment]
Browser: Chrome 131
![image](https://github.com/user-attachments/assets/7dcf48f5-c536-4f8f-8fae-4a87e599bc2d)
![image](https://github.com/user-attachments/assets/24c4c99e-a6a5-47f9-893e-50c6bdbfc400)
