### ISSUE TITLE
J個4叉欸死欸死嗎？（蝴蝶哽圖）

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [init-engineer/init.engineer#27]
![圖片](https://user-images.githubusercontent.com/13408130/77069893-35129a80-6a24-11ea-8e03-24ee5db88b90.png)

**描述錯誤**
參閱附圖：
![Screenshot_2020-03-19-19-31-50-707_org mozilla fenix](https://user-images.githubusercontent.com/13408130/77063397-95034400-6a18-11ea-84b7-cfb3fcb33bfa.jpg)
![Screenshot_20200319_222008](https://user-images.githubusercontent.com/13408130/77077227-e7039400-6a2f-11ea-89c7-6f81d5974dca.png)

**重現**
瀏覽 https://kaobei.engineer/cards/show/2526

**預期行為**
HTML 應該被消毒？

**Comment by Kantai235** [comment]
喔幹

**Comment by Kantai235** [comment]
已修正文章詳細內容有 XSS 漏洞的問題

**Comment by Lin-Buo-Ren** [comment]
不介意的話我就到站上發文囉
如果介意的話……那就不要 :heart:

**Comment by Kantai235** [comment]
# 淺談被靠北

- 活動時間：現在（[iCal/Outlook](https://localhost), [Google 日曆](https://localhost)）
- 活動地點：[純靠北工程師](https://kaobei.engineer)
- 報名人數：76115/無上限
- 主辦單位：[純靠北工程師](https://kaobei.engineer)
