### ISSUE TITLE
【乾爹許願】Apache 換 Nginx

### ISSUE THREAD

**Issue by Kantai235** [init-engineer/init.engineer#3]
![截圖 2019-11-26 下午4 19 35](https://user-images.githubusercontent.com/11679504/69611506-db4b2680-1068-11ea-8fd3-9ea7ee80cee4.png)

**Comment by seadog007** [comment]
強烈譴責掛上wontfix的行為
在此嚴重表達抗議

**Comment by Haraguroicha** [comment]
所以是到現在還是 Apache 嗎xDDDD？

**Comment by tico88612** [comment]
嗨！敝人知悉一些些 Docker，我把此系統轉到 Nginx，透過 Reverse Proxy 代理進去。  
歡迎各方高手、大師和大佬們的參考跟研究，謝謝 😁。  
https://github.com/tico88612/docker-init.engineer

**Comment by Kantai235** [comment]
有熱心網友解決了
https://github.com/init-engineer/init.engineer/issues/3#issuecomment-860135237
讚
