### ISSUE TITLE
大頭菜計算器原本來源API的輸出錯誤

### ISSUE THREAD

**Issue by LeoPengNekuros** [init-engineer/init.engineer#30]
**描述錯誤**
當菜價(買進) 93
週一 43/40
週二 36/31
週三 145/115 
填到145按計算的時候就會全部變成999

**截圖**

![image](https://user-images.githubusercontent.com/35591532/78743839-71d21180-7992-11ea-94e3-e63645a54b75.png)

**Comment by Kantai235** [comment]
感謝回報，我找個時間修一下

**Comment by LeoPengNekuros** [comment]
多提供幾個會測不出來的 (但理論上可以分析出是標準四期型)
當菜價(買進) 102
週一 92/112
週二 145/160
週三 167/163

**Comment by Kantai235** [comment]
跑版的問題、無法顯示的問題都已經在新的 Commit 當中獲得解決，並且部署至正式機當中。

剩餘的已知問題：
系統有兩種運算模式，一種是根據公式推估使用者是哪種模型，並且將結果透過彈出視窗的方式來顯示，基本上那是準的。
然後另一種是根據使用者輸入的鈴錢來把所有可能性的排列組合都列出來，並作統計後將其結果顯示在模型預測、價格預測當中，而這個錯誤會發生在沒有任何排列組合的資料時，才會發生這樣的錯誤，這部分後續會做修正。

**Comment by Kantai235** [comment]
在新的版本當中，這項問題已獲得修正。

![圖片](https://user-images.githubusercontent.com/11679504/79489313-a9edea00-804d-11ea-81a1-69958d53b32a.png)
