### ISSUE TITLE
iPhone XR Safari 無法使用大頭菜計算機圖表功能

### ISSUE THREAD

**Issue by wallaceinmo** [init-engineer/init.engineer#31]
**描述錯誤**
XR 手機瀏覽器 無法清楚看到預測圖表，使用Chrome 和 Safari 情況相同，在輸入部分數據時可成功顯示，但如截圖中數據則無法顯示

**重現**
重現行為的步驟：
1. 使用Safari輸入如圖中數據
2. 成功預測波型
3. 下方圖表仍舊無法顯示

**預期行為**
無法顯示圖表

**截圖**
如果適用，請添加螢幕截圖以幫助解釋您的問題。
![2DE72F54-7C67-4670-9333-A1149A8E85F8](https://user-images.githubusercontent.com/22535203/78747369-d6de3500-799b-11ea-843e-bd9f7907dbb6.png)
![881FB54C-A31C-4C17-90BC-880D97184FBE](https://user-images.githubusercontent.com/22535203/78747378-dc3b7f80-799b-11ea-8731-0ad6da5ff03c.png)
![48723D35-F82F-4346-9677-557E2FFE62F0](https://user-images.githubusercontent.com/22535203/78747388-e2316080-799b-11ea-81cd-a8139cbdbfa0.png)
![4B8CEFF0-BEA1-4173-9AF6-3899F9514FC4](https://user-images.githubusercontent.com/22535203/78747394-e8274180-799b-11ea-97be-b7f03a5c023e.png)

**裝置與環境(請填寫以下信息):**
* 設備: iPhone XR
* 操作系統: iOS 13.3.1
* 瀏覽器: Safari
* 版本:

**其他內容**
在此處添加有關該問題的任何其他上下文。

**Comment by Kantai235** [comment]
這項問題已於新的 Commit 當中解決，並且部署至正式機當中。

感謝您的回報 m(_ _)m
