### ISSUE TITLE
大頭菜計算機

### ISSUE THREAD

**Issue by Ming013** [init-engineer/init.engineer#32]
**描述錯誤**
無法使用計算機，跳出圓餅圖及預測價格

**重現**
重現行為的步驟：
1. 點擊上週波型‘遞減‘
2. 輸入買價、週一菜價
3.點擊輸入完畢

**預期行為**
跳出本週預測波型及價格

**截圖**
如果適用，請添加螢幕截圖以幫助解釋您的問題。

**裝置與環境(請填寫以下信息):**
* 設備：iphone8
* 操作系統: iOS 11.2
* 瀏覽器: Safari

**其他內容**
在此處添加有關該問題的任何其他上下文。

**Comment by Kantai235** [comment]
猜測是因為 Google Ad 自動廣告把預測結果給覆蓋掉了，目前已移除內容廣告，這項問題已獲得解決。
