### ISSUE TITLE
使用 Github 帳號登入時會出現「更新密碼」的告示

### ISSUE THREAD

**Issue by iigmir** [init-engineer/init.engineer#38]
**描述錯誤**
如題：使用 Github 帳號登入時，會出現「更新密碼」的指引。不過我不太確定這個錯誤出現的時機，只能說是一段時間後。

**重現**
重現行為的步驟：
1. 在尚未登入的情況下點選登入。
2. 在登入畫面點選「使用 Github 登入」
3. 等待不等的時間：可能幾分鐘、但也可能幾小時、甚至幾天。這段期間內不要登出。
4. 點選「發表文章」後，有機會讓問題出現。

**預期行為**
使用 Github 帳號登入時，不應該出現「更新密碼」的告示，因為我並沒有給網站設定密碼。還是說，網站會要求、以及更改我在 Github 帳號的密碼？

**截圖**
![Untitled2222](https://user-images.githubusercontent.com/11061770/82824587-2c36bd00-9edc-11ea-8229-6d47474f4fe6.gif)
（2020-05-24 登入， 2020-05-25 22.53.48 拍攝）

**裝置與環境(請填寫以下信息):**
* 設備：個人組裝的電腦
* 操作系統: Windows 10 Home 1909, Build 18363.836
* 瀏覽器: Mozilla Fireox
* 版本: 76.0.1

**其他內容**

**Comment by Kantai235** [comment]
更新密碼這件事應該是系統自動去追查的，目前是根據最後修改或者註冊時間往後算 1 年，有些動作會觸發這個事件的發生。

目前的解決方案是透過登入時的忘記密碼去重新設定密碼。

---
## 解決方式：
1. 在沒有登入的情況下，進入登入畫面選擇「忘記密碼」
2. 根據你 GitHub 的 Email 去走流程

**Comment by iigmir** [comment]
Hmm 我目前的方法，是先登出再登入耶。
![Untitled2222](https://user-images.githubusercontent.com/11061770/82824587-2c36bd00-9edc-11ea-8229-6d47474f4fe6.gif)

**Comment by Kantai235** [comment]
fix bug
