### ISSUE TITLE
Dashboard 頁面當沒有發表過文章時會有三個載入中的方框

### ISSUE THREAD

**Issue by jimmy-liao-gogoro** [init-engineer/init.engineer#52]
**描述錯誤**
Dashboard 頁面當沒有過發表文章時會有三個載入中的方框，
讓使用者以為還有資料在載入，但事實上並沒有。

**重現**
重現行為的步驟：
1. 當使用者完全沒有發表過文章
1. 使用者點右上角選單，再點選儀表板進入 Dashboard 頁面
1. 儀表板顯示：「沒有其他文章了。」
1. 但儀表板中間有三個正在載入中的方框

**預期行為**
不該有中間有三個正在載入中的方框，
會讓使用者以為有資料在載入，但其實並沒有。

**截圖**
![Screenshot](https://user-images.githubusercontent.com/52391190/88007342-61f4cc80-cb40-11ea-9dbe-7fbd0b2b284a.png)

**裝置與環境(請填寫以下訊息):**
* 設備: MacBook Pro (13-inch, 2017)
* 操作系統: 10.15.3
* 瀏覽器: Chrome
* 版本: Version 83.0.4103.116 (Official Build) (64-bit)

**其他內容**
無

**Comment by Kantai235** [comment]
fix bug
