### ISSUE TITLE
有一篇的全平台留言沒有出現噗浪的留言

### ISSUE THREAD

**Issue by Griiid** [init-engineer/init.engineer#57]
**描述錯誤**
https://kaobei.engineer/cards/show/5068 這篇看不到我在噗浪的留言

**重現**
不確定怎麼重現，不過我記得那一篇我曾經刪過回應再重新回。

**預期行為**
全平台留言中應該要出現噗浪上的留言。

**截圖**
直接看網頁就知道了 https://kaobei.engineer/cards/show/5068

**裝置與環境(請填寫以下訊息):**
我想應該是 Server 的問題，這邊就不留我裝置訊息了。

**其他內容**
加油。

**Comment by Kantai235** [comment]
兩年過去了，
DNS 更新了，
問題也解決了。
![圖片](https://user-images.githubusercontent.com/11679504/163247924-ba2734ce-d37c-40e4-bf57-714e273cd954.png)
