### ISSUE TITLE
功能請求：Sign in with Apple

### ISSUE THREAD

**Issue by tico88612** [init-engineer/init.engineer#63]
iOS App 上架 App Store 如果有使用第三方登入必須加入 Sign in with Apple 選項

參考：https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple

**Comment by tico88612** [comment]
已被完成 https://github.com/init-engineer/init.engineer/commit/bb75f61f8316d41cc0d2ed7ba27c27b27b4ff786，關閉此 Issue

**Comment by tico88612** [comment]
我以為是忘記關閉，原來是還沒完成。

![image](https://user-images.githubusercontent.com/17496418/108532342-b51b4180-7312-11eb-8313-41f2288f7150.png)

**Comment by Kantai235** [comment]
未來不會支援這項功能。
