### ISSUE TITLE
恭迎慈孤觀音主題，預覽會遮住文字

### ISSUE THREAD

**Issue by Griiid** [init-engineer/init.engineer#73]
**描述錯誤**
清楚簡明地描述錯誤是什麼。

**重現**
重現行為的步驟：
1. 到發文系統
2. 選主題「恭迎慈孤觀音......」
3. 輸入文字
4. 預覽會看到文字被圖片遮住

**預期行為**
預覽的文字應該不能被蓋住才對。

**截圖**
<img width="546" alt="截圖 2021-04-13 21 05 12" src="https://user-images.githubusercontent.com/17796098/114557398-33a1b900-9c9c-11eb-8511-6d737289f81e.png">

**裝置與環境(請填寫以下訊息):**
* 設備: MacBook Pro 15' 2018]
* 操作系統: macOS 11.2.3
* 瀏覽器: Firefox
* 版本: 87.0

**Comment by Kantai235** [comment]
酷欸

**Comment by Kantai235** [comment]
OK 問題已解決完畢


<img width="1148" alt="截圖 2021-04-26 01 15 25" src="https://user-images.githubusercontent.com/11679504/116002598-128e8000-a62d-11eb-8586-790f941f13c6.png">
