### ISSUE TITLE
疑似筆誤的敘述文字

### ISSUE THREAD

**Issue by EltonChou** [init-engineer/init.engineer#77]
https://github.com/init-engineer/init.engineer/blob/3408a33c433cab68be1e47098aacdc9373197b7f/resources/js/frontend/components/social/cards/SocialCardsCreate.vue#L1115

看 3408a33 的時候注意到的
感覺像是筆誤，但不確定是不是故意的

**Comment by Kantai235** [comment]
中文序順不響影閱讀

**Comment by Kantai235** [comment]
改天想到再來修

**Comment by Kantai235** [comment]
Fix bug
