### ISSUE TITLE
讓 title 與 site name 欄位正常一點

### ISSUE THREAD

**Issue by SoftwareSing** [init-engineer/init.engineer#80]
**您的功能要求與問題有關嗎？請描述。**

在 Discord 分享時，同樣的內容出現三次感覺很蠢 

![image](https://user-images.githubusercontent.com/36272700/125167760-aacfe600-e1d4-11eb-8446-30d128aea624.png)

https://init.engineer/cards/show/6638

---

**描述您想要的解決方案**

大概就這幾個地方

## site name

(這是出現在 Discord 預覽最上方那排小字)

```php
<meta name="twitter:site" content="@yield('meta_og_title', __('meta.twitter.site'))">
<meta property="og:site_name" content="@yield('title', app_name())">
```

按語意來說 `meta name="twitter:site"` 與 `meta property="og:site_name"`  的內容應該是網站名
顯示 `純靠北工程師` 即可，不用再接上文章內容

## title

(這是出現在 Discord 預覽中間藍藍的那個連結)

```php
<title>@yield('title', app_name())</title>
<meta name="twitter:title" content="@yield('meta_og_title', __('meta.og.title'))">
<meta property="og:title" content="@yield('meta_og_title', __('meta.og.title'))" />
```

`<title>` 把整篇文放進去有點太長
可能考慮切到第一個 `\n` 就好，或是單純顯示文章編號，並且將每個頁面獨特的內容放在前面
所以 `title` 的內容可能會變成 `「伺服器的資料庫沒辦法從外網連進來欸」 | 純靠北工程師` 或是 `#純靠北工程師54e | 純靠北工程師`

同理可能 `description` 就不用再重複出現 `純靠北工程師 | ` 這個開頭，因為標題已經描述過網站名了

---

**其他內容**
~~我看不懂 php ，所以發 issue 而不是 PR~~

**Comment by Kantai235** [comment]
我好棒，雖然不盡理想，但是越來越靠近理想了
<img width="569" alt="截圖 2022-04-12 18 50 28" src="https://user-images.githubusercontent.com/11679504/162944147-008127d2-30b1-4afa-8bfa-caabba1cc191.png">

**Comment by Kantai235** [comment]
我好棒，我現在觸及了理想。

![圖片](https://user-images.githubusercontent.com/11679504/164990395-137d66d5-43b4-435e-9169-96b48deb715b.png)
