### ISSUE TITLE
讓使用者可以在進入 4**/5** 頁面時，可以返回首頁

### ISSUE THREAD

**Issue by pan93412** [init-engineer/init.engineer#81]
**您的功能要求與問題有關嗎？請描述。**

目前的 4**/5** 頁面只有簡短的文字敘述，很容易讓使用者找不到回家的路。
所以我希望能夠讓純靠北系統在使用者可以在進入 4**/5** 頁面時，出現返回首頁的按鈕。

**描述您想要的解決方案**

在錯誤描述下方加上「返回首頁」，也能像學微博一樣放熱搜。

**其他內容**

乾太好電 :O

**Comment by Kantai235** [comment]
fix
