### ISSUE TITLE
回應的換行位置造成的排版問題

### ISSUE THREAD

**Issue by michaeimm** [init-engineer/init.engineer#9]
![CSS_IS_AWESOME](https://user-images.githubusercontent.com/14067477/70584407-faff5480-1bfb-11ea-9bac-3aeb12642e39.png)

CSS 完全に理解した！

**Comment by Kantai235** [comment]
過了快要半年，我終於解決了
修正文章留言在行動裝置上回應的換行位置造成的排版問題
