### ISSUE TITLE
送出文章，出現怪怪的 Alert

### ISSUE THREAD

**Issue by ajstudio-lin** [init-engineer/init.engineer#98]
只有怪怪的 Alert
沒有錯誤訊息
就叫我們來發 Issue
請問通靈嗎？

對，不能發文章靠爸，只能在這靠爸  ：））））））））））

好啦，送出文章，送不出，請看看是什麼問題吧 ＿＿＿＿

感恩！！

**Comment by Kantai235** [comment]
thx, i want to check check

**Comment by Kantai235** [comment]
有人說我上面留言太扯了，所以更正一下
thx, I will check the issue asap.

**Comment by Kantai235** [comment]
resolved 7af98d97dd444bdf82feba38e0bce3910dd80152
